// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCC38vlNCHcgnLeXOvprubIiHYaW-ZKuQ',
    appId: '1:350355329790:web:7f35b8e0094534fd8b0baf',
    messagingSenderId: '350355329790',
    projectId: 'fifthendtermact',
    authDomain: 'fifthendtermact.firebaseapp.com',
    storageBucket: 'fifthendtermact.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7hXoXFzrl9BOzTkh2sSeaxfnCLnOgOs',
    appId: '1:350355329790:android:eb8b015d524a68e18b0baf',
    messagingSenderId: '350355329790',
    projectId: 'fifthendtermact',
    storageBucket: 'fifthendtermact.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUbTGbOerrpTUuH4Jf-Fm3dyc9MX4MwQ',
    appId: '1:350355329790:ios:94138920a8ab26a38b0baf',
    messagingSenderId: '350355329790',
    projectId: 'fifthendtermact',
    storageBucket: 'fifthendtermact.firebasestorage.app',
    iosBundleId: 'com.example.fifthActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUbTGbOerrpTUuH4Jf-Fm3dyc9MX4MwQ',
    appId: '1:350355329790:ios:94138920a8ab26a38b0baf',
    messagingSenderId: '350355329790',
    projectId: 'fifthendtermact',
    storageBucket: 'fifthendtermact.firebasestorage.app',
    iosBundleId: 'com.example.fifthActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCC38vlNCHcgnLeXOvprubIiHYaW-ZKuQ',
    appId: '1:350355329790:web:9c1bdcc23988617c8b0baf',
    messagingSenderId: '350355329790',
    projectId: 'fifthendtermact',
    authDomain: 'fifthendtermact.firebaseapp.com',
    storageBucket: 'fifthendtermact.firebasestorage.app',
  );

}