// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAEvEM-9CM7wOr7IJcA4i_Z3UYXiIX2us',
    appId: '1:271769308304:web:7e5ba647f9296f8cd61c15',
    messagingSenderId: '271769308304',
    projectId: 'ndendtermact',
    authDomain: 'ndendtermact.firebaseapp.com',
    storageBucket: 'ndendtermact.firebasestorage.app',
    measurementId: 'G-KZS1TDGNLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZraKcELaHyxFHpf7B8XPsLI5TbZgc-TQ',
    appId: '1:271769308304:android:60ad8ec40c6fe55dd61c15',
    messagingSenderId: '271769308304',
    projectId: 'ndendtermact',
    storageBucket: 'ndendtermact.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8JNeI8G1IqY-kLy_Vx2wi2wRd9xlH78',
    appId: '1:271769308304:ios:3e2f30e65d66c8f5d61c15',
    messagingSenderId: '271769308304',
    projectId: 'ndendtermact',
    storageBucket: 'ndendtermact.firebasestorage.app',
    iosClientId:
        '271769308304-r87mrfe249utq9gu825pd7catnnvd7gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rojoendterm2ndact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8JNeI8G1IqY-kLy_Vx2wi2wRd9xlH78',
    appId: '1:271769308304:ios:3e2f30e65d66c8f5d61c15',
    messagingSenderId: '271769308304',
    projectId: 'ndendtermact',
    storageBucket: 'ndendtermact.firebasestorage.app',
    iosClientId:
        '271769308304-r87mrfe249utq9gu825pd7catnnvd7gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rojoendterm2ndact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAEvEM-9CM7wOr7IJcA4i_Z3UYXiIX2us',
    appId: '1:271769308304:web:3d5abd0640e60a6dd61c15',
    messagingSenderId: '271769308304',
    projectId: 'ndendtermact',
    authDomain: 'ndendtermact.firebaseapp.com',
    storageBucket: 'ndendtermact.firebasestorage.app',
    measurementId: 'G-EGS1VLHD7S',
  );
}
